# ============================
# Configuración de experimento
# ============================
experiment:
  model: "solid"   # nombre corto del modelo (baseline, solid, etc.)
  mode: "fe_off"
  seed: 42            # semilla fija para reproducibilidad

# ============================
# Configuración de datos
# ============================
data:
  train_dir: "/home/michell-alvarez/e_modelos/EF/Violencia/Train"
  test_dir: "/home/michell-alvarez/e_modelos/EF/Violencia/Test"
  classes: ["NonViolence", "Violence"]
  num_classes: 2
  
  # Preprocesado
  frame_size: 112     # tamaño al que se redimensiona cada frame (ej. 112x112)
  clip_len: 16 #num_frames: 16      # número de frames por video
  augment: true
  

# ============================
# Parámetros de entrenamiento
# ============================
training:
  batch_size: 16
  epochs: 50
  #learning_rate: 0.001
  early_stop_patience: 15
  train_split: 0.8
  val_split: 0.2
  num_workers: 8 
  lr: 0.001
  weight_decay: 0.0001
  amp: true
  min_delta: 0.005
  label_smoothing: 0.1
  #lr=1e-3
    
# ============================
# Configuración del modelo
# ============================
model:
  name: "ViolenceDetector"
  channels: [8, 16, 32]
  dropout: 0.3

# ============================
# Rutas base y derivadas
# ============================
paths:
  base_outputs: "outputs"          # carpeta raíz donde se crearán los run_id
  index_file: "data/video_index.csv"
  train_index: "data/train_index.csv"
  test_index: "data/test_index.csv"
  checkpoints: "checkpoints"      # se sobrescribirá dinámicamente por run_id
  log_txt: "logs/training.log"        # idem 
  #run_root: "outputs/baseline/2025-10-05_13-13-39"   # comenta si no es fijo
  #best_ckpt: "outputs/best_model.pth"

  


  

  
